### ISSUE TITLE
How to add dataset

### ISSUE THREAD

**Issue by vfdev-5** [dmitry-vorobiev/generative-models#1]
Hi @dmitry-vorobiev 

I'm trying to play around this code and it would cool to add some info on:
- how to download the dataset 
- how to use the dataset from a custom location

What do you think ?

PS: thanks for open-sourcing the code

**Comment by dmitry-vorobiev** [comment]
Hi @vfdev-5
The initial plan was to instantiate the datasets from a config file. The current way it's done might be far from optimal and is subject to change.

You can rewrite `create_train_loader` function in `train_gan.py` as you want. Or you may add a link to your own function, which can instantiate your own dataset class here: 

```python
# src/train_gan.py

def create_train_loader(conf, rank=None, num_replicas=None):
    # type: (DictConfig, Optional[int], Optional[int]) -> Sized
    build_ds = {
        'simple': create_simple_dataset
        'my_dataset': create_my_dataset
    }
    collate_funcs = {
        'simple': default_collate_no_labels,
        # the train loop expects the dataloader to return tuple of tensors: 
        # (images, labels) or (images, None)
        'my_dataset': None
    }

# conf corresponds to the "data" section of the config file
def create_my_dataset(conf, transforms):
    # type: (DictConfig, DictConfig) -> JustImages
    transforms = T.Compose([instantiate(v) for k, v in transforms.items()])
    ds = MyDataset(conf.root, extensions=tuple(conf.extensions), transform=transforms)
    return ds
```

The data location and other parameters comes from the *data* section of the config file (`config/train_gan.yaml` by default). So you may want to change these lines:
```yaml
data:
  root: /media/dmitry/data/ffhq-dataset/thumbnails128x128
  extensions:
    - png
```

I use [config composition](https://hydra.cc/docs/tutorial/composition), so half of the settings comes from `config/dataset/simple.yaml`. One option is to add a similar file under the `config/dataset` folder and have a link to it in the `train_gan.yaml`:

```yaml
# config/dataset/my_dataset.yaml
data:
  type: my_dataset
  transforms:
```

```yaml
# config/train_gan.yaml
defaults:
  - dataset: my_dataset
```

Or you may just remove these lines and add all your settings directly to the `train_gan.yaml` *data* section. The are many ways you can achieve this with [hydra](https://hydra.cc/)
